CREATE TABLE regions(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE qualifications(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE levels(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL
);
