server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: auth
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: 123123
  flyway:
    locations: classpath:migrations
  mvc:
    throw-exception-if-no-handler-found: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
ribbon:
  eureka:
    enabled: false