server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: 123123
  flyway:
    locations: classpath:migrations
  mvc:
    throw-exception-if-no-handler-found: true
pkr:
  services:
    auth:
      url: http://localhost:8085
